import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { NextAuthProvider } from "./components/providers/NextAuthProvider";

const nextFont = Montserrat({
  style: ['normal', 'italic'],
  subsets: ['latin'],
  weight: ['400', '700'],
  preload:false
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="https://gnubvphzxvsihriukkdr.supabase.co/storage/v1/object/public/nextjs/o-logo.png" />
      </head>
      <body className={nextFont.className}>
        <NextAuthProvider>
          {children}
        </NextAuthProvider>
        <SpeedInsights />
      </body>
    </html>
  );
}
